import { Box, BookOpen, Compass, Sparkles, Gauge, CheckCircle2, ChevronRight, Clock3, Map } from 'lucide-react';
import { PanelTitle, Stat, type Screen } from '../shared';

export function Dashboard({ setScreen }: { setScreen: (screen: Screen) => void }) {
  return <div className="dashboard">
    <section className="hero-banner"><div className="hero-stars" /><div className="hero-earth" /><div className="hero-copy"><span className="identity-kicker"><span className="kicker-line" /> COMMAND OVERVIEW</span><h1>Explore. Observe. Navigate.</h1><p>Master the universe.</p></div><div className="hero-stats"><Stat value="12" label="Courses" sub="In Progress" /><Stat value="07" label="Simulations" sub="Completed" /><Stat value="85%" label="Overall" sub="Progress" /><Stat value="04" label="Upcoming" sub="Sessions" /></div></section>
    <div className="dashboard-grid">
      <section className="panel quick-panel"><PanelTitle title="Quick Access" action="View all" /><div className="quick-grid">{[{ icon: Box, label: '3D', sub: 'Planetarium', screen: 'planetarium' as Screen }, { icon: Compass, label: 'Navigation', sub: 'Trainer', screen: 'navigation' as Screen }, { icon: Sparkles, label: 'AI Tutor', sub: 'Ask anything', screen: 'aitutor' as Screen }, { icon: Gauge, label: 'Simulations', sub: 'Practice', screen: 'simulations' as Screen }].map(({ icon: Icon, label, sub, screen }) => <button key={label} onClick={() => setScreen(screen)}><span className="quick-icon"><Icon size={25} /></span><strong>{label}</strong><small>{sub}</small></button>)}</div></section>
      <section className="panel progress-panel"><PanelTitle title="My Progress" action="View details" /><div className="progress-content"><div className="ring-chart"><div><strong>72%</strong><span>Completed</span></div></div><div className="progress-legend"><div><i className="blue-dot" />Completed <b>18</b></div><div><i className="gray-dot" />In Progress <b>12</b></div><div><i className="light-dot" />Not Started <b>06</b></div><div><i className="dark-dot" />Total Courses <b>36</b></div></div></div><button className="continue-link" onClick={() => setScreen('progress')}>Continue Learning <ChevronRight size={15} /></button></section>
      <section className="panel session-panel"><PanelTitle title="Next Session" action="View calendar" /><div className="session-label"><span className="session-status">UPCOMING</span><strong>Celestial Navigation — Level 2</strong></div><p><Clock3 size={14} /> 20 May 2025 · 10:00 AM PKT</p><p><Map size={14} /> Virtual Bridge · Room 3</p><button className="blue-button" onClick={() => setScreen('live')}>Join Session <ChevronRight size={15} /></button></section>
    </div>
    <div className="dashboard-grid lower"><ActivityPanel /><Achievements /></div>
  </div>;
}

function ActivityPanel() { return <section className="panel activity-panel"><PanelTitle title="Recent Activity" action="View all" /><div className="activity-list">{[['Completed Simulation', 'Star Identification Drill', 'Today, 11:20 AM', CheckCircle2], ['AI Assessment Passed', 'Celestial Basics · Quiz', 'Today, 09:45 AM', Sparkles], ['Course Progress', 'Celestial Navigation Level 2', 'Yesterday, 08:30 PM', BookOpen]].map(([title, sub, time, Icon]) => { const ActivityIcon = Icon as typeof CheckCircle2; return <div className="activity-row" key={title as string}><span className="activity-icon"><ActivityIcon size={15} /></span><div><strong>{title as string}</strong><small>{sub as string}</small></div><time>{time as string}</time></div>; })}</div></section>; }
function Achievements() { return <section className="panel achievement-panel"><PanelTitle title="Achievements" action="View all" /><div className="achievement-list">{[['✦', 'Star Explorer', 'Identify 50 Stars'], ['⚓', 'Navigator', 'Complete Level 1'], ['◉', 'Observer', '10 Simulations'], ['✧', 'Precision', '90% Accuracy'], ['◆', 'Dedicated', '7-Day Streak']].map(([icon, title, sub]) => <div key={title} className="achievement"><span>{icon}</span><strong>{title}</strong><small>{sub}</small></div>)}</div></section>; }
